<a href="https://colab.research.google.com/github/pablozamudio/workshop-categorizacion-productos/blob/master/intro_python_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

# Python Basics

Function Definition

In [1]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

Optional parameters

In [2]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


Assing functions to variables

In [3]:
a = add_numbers
a(1,2)

3

In [4]:
type('This is a string')

str

In [5]:
type(add_numbers)

function

Tuples are inmutable

In [6]:
x = (1, 'a', 2, 'b')
type(x)

tuple

Lists are mutable

In [7]:
x = [1, 'a', 2, 'b']
type(x)

list

In [8]:
x.append('Something')
x

[1, 'a', 2, 'b', 'Something']

For loops

In [9]:
for item in x:
    print(item)

1
a
2
b
Something


Concat Lists

In [10]:
[1,2] + [3,4]

[1, 2, 3, 4]

Repeat list

In [11]:
[1]*3

[1, 1, 1]

Slice from string

In [12]:
x = 'This is a string'
print(x[:2]) # First 2 chars
print(x[-1]) # Last char
print(x[-4:-2]) # Slice starting from the end 

Th
g
ri


Dictionaries

In [13]:
x = {'A':1, 'B': 2}
x['A']

1

In [0]:
x['A']=None
x['A']

# Numpy Basics
- Linear Algebra
- Provee high-performance multidimensional arrays y tools para trabajar con éstos.

## Arrays
Son grillas de valores, todos del mismo tipo.

In [18]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [19]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)

(2, 3)


In [20]:
print(b[0, 1])
print(b[1, 0])

2
4


Useful functions

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.full((2,3), 3)

array([[3, 3, 3],
       [3, 3, 3]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
a = np.random.random((2,2))
a

array([[0.85895226, 0.38351595],
       [0.79050712, 0.17384071]])

In [26]:
print(a.dtype) 

float64


## Vectorization

Vector multiplication using for loops

In [27]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
    
print("Non vectorized version: " + str(1000*(toc-tic)) + " ms")
print("Output value:", c)

Non vectorized version: 398.9453315734863 ms
Output value: 250012.5689066717


Vector multiplication using vectorized version

In [28]:
tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorized version: " + str(1000*(toc-tic)) + " ms")
print("Output value:", c)

Vectorized version: 14.351606369018555 ms
Output value: 250012.56890667003


# Pandas

## Series

In [0]:
import pandas as pd
pd.Series?

In [30]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [31]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [32]:
animals = ['Tiger', 'Bear', None]
pd.Series(animals)

0    Tiger
1     Bear
2     None
dtype: object

In [33]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [34]:
import numpy as np
np.nan == None

False

In [35]:
np.nan == np.nan

False

In [36]:
np.isnan(np.nan)

True

Querying a series

In [38]:
a = {'A': 'VA',
      'B': 'VB',
      'C': 'VC',
      'D': 'VD'}
s = pd.Series(a)
s

A    VA
B    VB
C    VC
D    VD
dtype: object

In [39]:
s.iloc[3]

'VD'

In [40]:
s.loc['D']

'VD'

In [41]:
s[3]

'VD'

In [42]:
s['D']

'VD'

In [0]:
a = {10: 'VA',
          11: 'VB',
          12: 'VC',
          13: 'VD'}
s = pd.Series(a)

In [44]:
s.iloc[0]

'VA'

In [48]:
s[0]

KeyError: ignored

## DataFrame

In [62]:
d = {'one': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
df.head()

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [63]:
print(df.index)

Index(['a', 'b', 'c', 'd'], dtype='object')


In [64]:
df.loc['c']

one    3.0
two    3.0
Name: c, dtype: float64

In [65]:
df.T

a    b    c    d
one  1.0  2.0  3.0  NaN
two  1.0  2.0  3.0  4.0

In [66]:
df.T.loc['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [0]:
df = df.drop('a')

In [68]:
df

one  two
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [69]:
copy_df = df.copy()
copy_df = copy_df.drop('c')
copy_df

one  two
b  2.0  2.0
d  NaN  4.0

In [70]:
df

one  two
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

Query a DataFrame

In [71]:
df['two'] > 2

b    False
c     True
d     True
Name: two, dtype: bool

In [75]:
df.where(df['two'] > 2)

one  two
b  NaN  NaN
c  3.0  3.0
d  NaN  4.0

In [76]:
df.where(df['two'] > 2).dropna()

one  two
c  3.0  3.0

In [77]:
df[df['two'] > 2]

one  two
c  3.0  3.0
d  NaN  4.0